rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 0.25.2-sp
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: java7
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.2.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.12.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.6.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.19.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.20.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.23.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
  - pattern: 1.33.x-LTS8
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - cla/google
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
permissionRules:
  - team: Googlers
    permission: pull
  - team: yoshi-java
    permission: push
  - team: java-samples-reviewers
    permission: push
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-admins
    permission: admin
  - team: googleapis-auth
    permission: admin
  - team: aion-sdk
    permission: push
